# Generated by Django 2.0.7 on 2018-07-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter_project', '0002_twit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='re_twit',
            field=models.ManyToManyField(blank=True, null=True, related_name='retwit', to=settings.AUTH_USER_MODEL, verbose_name='Ретвит'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
