# Generated by Django 2.0.7 on 2018-07-12 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_project', '0003_auto_20180712_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='re_twit',
            field=models.ManyToManyField(related_name='retwit', to=settings.AUTH_USER_MODEL, verbose_name='Ретвит'),
        ),
    ]
