# Generated by Django 2.0.7 on 2018-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_project', '0005_twit_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='text',
            field=models.CharField(max_length=251),
        ),
    ]
